### ISSUE TITLE
Should minigames be random? 

### ISSUE THREAD

**Issue by ZedXC** [tessapower/ggj-2024#23]
In a recent change the game.gd file was changed to make it so minigames ran in a queue in the same order every time? Not sure if this is intentional or now

**Comment by tessapower** [comment]
I'm in two minds about it, so here are some options I've thought of:

- We shuffle them to start with so the games appear in a new random order (easy to keep track of rounds and know when to increase speed, player plays each game at least once each round, maybe less fun because predictable)
- We make the next game totally random, and each round consists of the player playing x number of mini-games regardless of what they are (chaotic and fun, need to track number of games played each round, some mini-games may get played less)

**Comment by ZedXC** [comment]
I think we should do the first option where we shuffle them so each round has a selection of different games. I think rounds shouldn't be too long though so maybe like 3-4 games per round that way some games aren't there meaning there's a bit more mystery about which games you're gonna get

**Comment by ZedXC** [comment]
Minigames will be round based sorted into 3 minigames from the options available.
